SELECT * FROM TBL_TRAIN;
SELECT * FROM TBL_BUS;
SELECT * FROM TBL_CAMP;
SELECT * FROM TBL_AIR;
SELECT * FROM TBL_PARK;
SELECT * FROM TBL_HOTEL;
SELECT * FROM TBL_WEATHER;
SELECT * FROM TBL_PHOTO;
SELECT * FROM
(SELECT ROWNUM NUM, 
 					 NO, 
 					 TITLE,
 					 CONT,
 					 REVSTAR,
 					 REVLIKE,
 					 CREATEDATE,
 					 MEMBERNO, 
 					 CAMPNO, 
 					 HOTELNO, 
 					 FESTIVALNO, 
 					 FOODNO, 
 					 PARKNO  FROM 
(SELECT * FROM TBL_REVIEW ORDER BY no DESC))
WHERE NUM <= 5 AND MEMBERNO = 2;

update tbl_member set pwd = '1234' where no = 2;
commit;

DROP TABLE "TBL_REPLY";
DELETE "TBL_RESERVE";

update tbl_member set dong='논현동' where no=2;

INSERT INTO tbl_member VALUES(MEMBER_SEQ.NEXTVAL, 'admin', '1234', '관리자', '01012312323','admin@admin.com','역삼동');

-- test 구역
SELECT type FROM TBL_FOOD where NAME='서령';
SELECT theme FROM TBL_CAMP group by theme;

TRUNCATE table tbl_train;
TRUNCATE table TBL_FOOD;
TRUNCATE table TBL_HOTEL;
TRUNCATE table TBL_WEATHER;

SELECT *
FROM TBL_RESERVE
WHERE MEMBERNO = 2 AND CAMPNO != 0
ORDER BY RESERVEDATE ASC;

-- 예약 테스트
INSERT INTO TBL_RESERVE VALUES(RESERVE_SEQ.NEXTVAL,SYSDATE,SYSDATE,'',5,60000,2,18561,0,0,0,0);
INSERT INTO TBL_RESERVE VALUES(RESERVE_SEQ.NEXTVAL,SYSDATE,SYSDATE,'',5,60000,2,0,4,0,0,0);
INSERT INTO TBL_RESERVE VALUES(RESERVE_SEQ.NEXTVAL,SYSDATE,SYSDATE,'',5,60000,2,0,0,1,0,0);
INSERT INTO TBL_RESERVE VALUES(RESERVE_SEQ.NEXTVAL,SYSDATE,SYSDATE,'06:20',5,60000,2,0,0,0,1,0);
INSERT INTO TBL_RESERVE VALUES(RESERVE_SEQ.NEXTVAL,SYSDATE,SYSDATE,'',5,60000,2,0,0,0,0,1);

INSERT INTO TBL_LIKE VALUES(LIKE_SEQ.NEXTVAL,2,18561,0,0,0,0); -- 호텔 캠프 축제 음식 공원
INSERT INTO TBL_LIKE VALUES(LIKE_SEQ.NEXTVAL,2,0,4,0,0,0);
INSERT INTO TBL_LIKE VALUES(LIKE_SEQ.NEXTVAL,2,0,0,3833,0,0);
INSERT INTO TBL_LIKE VALUES(LIKE_SEQ.NEXTVAL,2,0,0,0,3,0);
INSERT INTO TBL_LIKE VALUES(LIKE_SEQ.NEXTVAL,2,0,0,0,0,35711);

INSERT INTO TBL_REVIEW VALUES(REVIEW_SEQ.NEXTVAL,'제목','내용',4,50,SYSDATE,2,18561,0,0,0,0); -- 호텔 캠프 축제 음식 공원
INSERT INTO TBL_REVIEW VALUES(REVIEW_SEQ.NEXTVAL,'제목','내용',5,50,SYSDATE,2,0,4,0,0,0);
INSERT INTO TBL_REVIEW VALUES(REVIEW_SEQ.NEXTVAL,'제목','내용',3,50,SYSDATE,2,0,0,3833,0,0);
INSERT INTO TBL_REVIEW VALUES(REVIEW_SEQ.NEXTVAL,'제목','내용',4,50,SYSDATE,2,0,0,0,3,0);
INSERT INTO TBL_REVIEW VALUES(REVIEW_SEQ.NEXTVAL,'제목','내용',3,50,SYSDATE,2,0,0,0,0,35711);

INSERT INTO TBL_PHOTO VALUES(PHOTO_SEQ.NEXTVAL,'제목','내용',100,'캠핑장','','',SYSDATE,SYSDATE,2);
INSERT INTO TBL_BOARD VALUES(BOARD_SEQ.NEXTVAL,'제목','내용',100,SYSDATE,SYSDATE,2);

INSERT INTO TBL_REPLY VALUES(REPLY_SEQ.NEXTVAL,'제목','내용',SYSDATE,SYSDATE,2,1);
commit;

-- NO 0으로 설정해서 예약에 활용
INSERT INTO TBL_TRAIN VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TBL_CAMP VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TBL_BUS VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TBL_AIR VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TBL_HOTEL VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TBL_PARK VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TBL_FOOD VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TBL_FESTIVAL VALUES(0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

create SEQUENCE TRAIN_SEQ;
drop SEQUENCE TRAIN_SEQ;

create SEQUENCE BUS_SEQ;
drop SEQUENCE BUS_SEQ;

create SEQUENCE AIR_SEQ;
drop SEQUENCE AIR_SEQ;

create SEQUENCE HOTEL_SEQ;
drop SEQUENCE HOTEL_SEQ;

create SEQUENCE FOOD_SEQ;
drop SEQUENCE FOOD_SEQ;

create SEQUENCE PARK_SEQ;
drop SEQUENCE PARK_SEQ;

create SEQUENCE FESTIVAL_SEQ;
drop SEQUENCE FESTIVAL_SEQ;

create SEQUENCE MEMBER_SEQ;
drop SEQUENCE MEMBER_SEQ;

create SEQUENCE RESERVE_SEQ;
drop SEQUENCE RESERVE_SEQ;

create SEQUENCE BOARD_SEQ;
drop SEQUENCE BOARD_SEQ;

create SEQUENCE PHOTO_SEQ;
drop SEQUENCE PHOTO_SEQ;

create SEQUENCE LIKE_SEQ;
drop SEQUENCE LIKE_SEQ;

create SEQUENCE REVIEW_SEQ;
drop SEQUENCE REVIEW_SEQ;

create SEQUENCE REPLY_SEQ;
drop SEQUENCE REPLY_SEQ;


CREATE TABLE "TBL_MEMBER" (
	NO	NUMBER		NOT NULL,
	ID	VARCHAR2(1000)		NULL,
	PWD	VARCHAR2(1000)		NULL,
	NAME	VARCHAR2(1000)		NULL,
	PHONE	VARCHAR2(1000)		NULL,
	EMAIL 	VARCHAR2(1000)		NULL,
	DONG	VARCHAR2(1000)		NULL
);

CREATE TABLE "TBL_TRAIN" (
	NO	NUMBER		NOT NULL,
    STARTSTA	VARCHAR2(1000)		NULL,
    ENDSTA	VARCHAR2(1000)		NULL,
    STARTLAT    VARCHAR2(1000)		NULL,
    STARTLNG    VARCHAR2(1000)		NULL,
    ENDLAT      VARCHAR2(1000)		NULL,
    ENDLNG      VARCHAR2(1000)		NULL,
    STARTTIME	VARCHAR2(1000)		NULL,
    ENDTIME	VARCHAR2(1000)		NULL,
    WASTETIME	VARCHAR2(1000)		NULL,
    SPECIALPRICE	VARCHAR2(1000)		NULL,
    GENERALPRICE	VARCHAR2(1000)		NULL,
    TRAINCLASS	VARCHAR2(1000)		NULL,
    RAILNAME	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "TBL_TRAIN".trainclass IS 'KTX';

COMMENT ON COLUMN "TBL_TRAIN".railname IS 'KTX경부선';

CREATE TABLE "TBL_CAMP" (
	NO	NUMBER		NOT NULL,
	NAME	 VARCHAR2(1000)		NULL,
	LINEINTRO	VARCHAR2(1000)		NULL,
	ARIA	VARCHAR2(1000)		NULL,
	CATEGORY	VARCHAR2(1000)		NULL,
	ADDR	VARCHAR2(1000)		NULL,
	LAT	VARCHAR2(1000)		NULL,
	LNG	VARCHAR2(1000)		NULL,
	PRICE	VARCHAR2(1000)		NULL,
	PHONE	VARCHAR2(1000)		NULL,
	HOMEPAGE	VARCHAR2(1000)		NULL,
	SUB	VARCHAR2(1000)		NULL,
	THEME	VARCHAR2(1000)		NULL,
	IMAGE	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "TBL_CAMP"."category" IS '클램핑/카라반 등';

CREATE TABLE "TBL_BUS" (
	NO	NUMBER		NOT NULL,
	STARTSTA	VARCHAR2(1000)		NULL,
	ENDSTA	VARCHAR2(1000)		NULL,
	STARTLAT	VARCHAR2(1000)		NULL,
	STARTLNG	VARCHAR2(1000)		NULL,
	ENDLAT	VARCHAR2(1000)		NULL,
	ENDLNG	VARCHAR2(1000)		NULL,
	WASTETIME	VARCHAR2(1000)		NULL,
	SCHEDULE	VARCHAR2(4000)		NULL,
    NIGHTSCHEDULE	VARCHAR2(4000)		NULL,
	NORMALRPICE	VARCHAR2(1000)		NULL,
	NIGHTPRICE	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "TBL_BUS".no IS '시퀀스';

COMMENT ON COLUMN "TBL_BUS".schedule IS '받아올 때 파싱';

CREATE TABLE "TBL_AIR" (
	NO	NUMBER		NOT NULL,
	STARTSTA	VARCHAR2(1000)		NULL,
	ENDSTA	VARCHAR2(1000)		NULL,
	PRICE	VARCHAR2(1000)	NULL,
	STARTTIME	VARCHAR2(1000)		NULL,
	ENDTIME VARCHAR2(1000)		NULL,
	FLIGHT	VARCHAR2(1000)		NULL,
	AIRLINE	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "TBL_AIR".no IS '시퀀스';

CREATE TABLE "TBL_AIRCOOR" (
    sta	VARCHAR(1000)		NULL,
    lat	VARCHAR(1000)		NULL,
     lng	VARCHAR(1000)		NULL
 );

CREATE TABLE "TBL_FOOD" (
    NO NUMBER NULL,
    NAME	 VARCHAR(1000)		NULL,
    ADDR	VARCHAR(1000)		NULL,
    TYPE	VARCHAR(1000)		NULL,
    MAIN VARCHAR(1000)		NULL,
    PHONE	VARCHAR(1000)		NULL,
    LAT	VARCHAR(1000)		NULL,
    LNG	VARCHAR(1000)		NULL
);
	
CREATE TABLE "TBL_HOTEL" (
    NO	NUMBER		NOT NULL,
    PHONE 	VARCHAR(1000)		NULL,
    ADDR 	VARCHAR(1000)		NULL,
    NAME 	VARCHAR(1000)		NULL,
    PRICE 	VARCHAR(1000)		NULL,
    LAT	VARCHAR(1000)		NULL,
    LNG	VARCHAR(1000)		NULL
);
	
CREATE TABLE "TBL_WEATHER" (
    GU	VARCHAR(1000)		NULL,
    DONG	VARCHAR(1000)		NULL,
    NX	VARCHAR(1000)		NULL,
    NY	VARCHAR(1000)		NULL
);
	
CREATE TABLE "TBL_PARK" (
    NO	NUMBER		NOT NULL,
    NAME VARCHAR2(1000) NULL,
    CATEGORY	VARCHAR(1000)		NULL,
    ADDR	VARCHAR(1000)		NULL,
    LAT	VARCHAR(1000)		NULL,
    LNG	VARCHAR(1000)		NULL,
    SPORT	 VARCHAR(1000)		NULL,
    PHONE	VARCHAR(1000)		NULL
);
	
CREATE TABLE "TBL_FESTIVAL" (
    NO	NUMBER	 NOT NULL,
    NAME 	VARCHAR(1000)		NULL,
    PLACE 	VARCHAR(1000)		NULL,
    STARTDATE	DATE		NULL,
    ENDDATE 	DATE	NULL,
    CONT	VARCHAR(1000)		NULL,
    PHONE	VARCHAR(1000)		NULL,
    HOMEPAGE	VARCHAR(1000)		NULL,
    ADDR	VARCHAR(1000)		NULL,
    LAT	VARCHAR(1000)		NULL,
    LNG	VARCHAR(1000)		NULL
);

CREATE TABLE "TBL_RESERVE" (
    NO	NUMBER		NOT NULL,
	PAYDATE	DATE	DEFAULT SYSDATE	NULL,
	RESERVEDATE	DATE		NULL,
    STARTTIME VARCHAR2(1000) NULL,
	COUNT	NUMBER		NULL,
	PRICE	NUMBER		NULL,
	MEMBERNO	NUMBER		NULL,
	HOTELNO	NUMBER		NULL,
	CAMPNO	NUMBER		NULL,
	AIRNO	NUMBER		NULL,
	BUSNO	NUMBER		NULL,
	TRAINNO	NUMBER		NULL
);

CREATE TABLE "TBL_LIKE" (
	NO	NUMBER		NOT NULL,
	MEMBERNO	NUMBER		NOT NULL,
	HOTELNO	NUMBER		NULL,
	CAMPNO	NUMBER		NULL, -- 
	FESTIVALNO	NUMBER		NULL,
	FOODNO	NUMBER		NULL,
	PARKNO	NUMBER		NULL
);

CREATE TABLE "TBL_REVIEW" (
	NO	NUMBER		NOT NULL,
	TITLE	VARCHAR2(1000)		NULL,
	CONT	 VARCHAR2(1000)		NULL,
	REVSTAR 	NUMBER	DEFAULT 5	NULL,
	REVLIKE  	NUMBER	DEFAULT 0	NULL,
	CREATEDATE  	DATE	DEFAULT SYSDATE	NULL,
	MEMBERNO	NUMBER		NOT NULL,
	HOTELNO	    NUMBER		NULL,
	CAMPNO	NUMBER		NULL,
	FESTIVALNO	NUMBER		NULL,
	FOODNO	NUMBER		NULL,
	PARKNO	NUMBER		NULL
);

CREATE TABLE "TBL_REPLY" (
	NO	NUMBER		NOT NULL,
    TITLE VARCHAR2(1000) NULL,
	CONT	VARCHAR2(1000)		NULL,
	CREATEDATE DATE	DEFAULT SYSDATE	NULL,
	MODIFYDATE	DATE		NULL,
	MEMBERNO	NUMBER		NOT NULL,
	PHOTONO	NUMBER		NOT NULL
);

CREATE TABLE "TBL_PHOTO" (
	NO	NUMBER		NOT NULL,
	TITLE	VARCHAR2(1000)		NULL,
	CONT	VARCHAR2(1000)		NULL,
	READCOUNT	NUMBER		NULL,
	CATEGORY	VARCHAR2(1000)		NULL,
	ORIGINALFILE	VARCHAR2(1000)		NULL,
	RENAMEFILE	 VARCHAR2(1000)		NULL,
	CREATEDATE	 DATE	 DEFAULT SYSDATE 	NULL,
	MODIFYDATE	DATE		NULL,
	MEMBERNO	NUMBER		NOT NULL
);
COMMENT ON COLUMN "TBL_PHOTO".CATEGORY IS '캠핑장 등';

CREATE TABLE "TBL_BOARD" (
	NO	NUMBER		NOT NULL,
	TITLE	VARCHAR2(1000)		NULL,
	CONT	VARCHAR2(1000)		NULL,
	READCOUNT	NUMBER		NULL,
	CREATEDATE DATE	DEFAULT SYSDATE	NULL,
	MODIFYDATE	DATE		NULL,
	MEMBERNO	NUMBER		NOT NULL
);

ALTER TABLE "TBL_TRAIN" ADD CONSTRAINT "PK_TBL_TRAIN" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_CAMP" ADD CONSTRAINT "PK_TBL_CAMP" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_BUS" ADD CONSTRAINT "PK_TBL_BUS" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_AIR" ADD CONSTRAINT "PK_TBL_AIR" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_FOOD" ADD CONSTRAINT "PK_TBL_FOOD" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_HOTEL" ADD CONSTRAINT "PK_TBL_HOTEL" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_PARK" ADD CONSTRAINT "PK_TBL_PARK" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_FESTIVAL" ADD CONSTRAINT "PK_TBL_FESTIVAL" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_MEMBER" ADD CONSTRAINT "PK_TBL_MEMBER" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_RESERVE" ADD CONSTRAINT "PK_TBL_RESERVE" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "PK_TBL_LIKE" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_REVIEW" ADD CONSTRAINT "PK_TBL_REVIEW" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_REPLY" ADD CONSTRAINT "PK_TBL_REPLY" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_PHOTO" ADD CONSTRAINT "PK_TBL_PHOTO" PRIMARY KEY (
    NO
);

ALTER TABLE "TBL_BOARD" ADD CONSTRAINT "PK_TBL_BOARD" PRIMARY KEY (
	NO
);

ALTER TABLE "TBL_RESERVE" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_RESERVE_1" FOREIGN KEY (
	MEMBERNO
)
REFERENCES "TBL_MEMBER" (
	NO
);

ALTER TABLE "TBL_RESERVE" ADD CONSTRAINT "FK_TBL_HOTEL_TO_TBL_RESERVE_1" FOREIGN KEY (
	HOTELNO
)
REFERENCES "TBL_HOTEL" (
	NO
);

ALTER TABLE "TBL_RESERVE" ADD CONSTRAINT "FK_TBL_CAMP_TO_TBL_RESERVE_1" FOREIGN KEY (
	CAMPNO
)
REFERENCES "TBL_CAMP" (
	NO
);

ALTER TABLE "TBL_RESERVE" ADD CONSTRAINT "FK_TBL_AIR_TO_TBL_RESERVE_1" FOREIGN KEY (
	AIRNO
)
REFERENCES "TBL_AIR" (
	NO
);

ALTER TABLE "TBL_RESERVE" ADD CONSTRAINT "FK_TBL_BUS_TO_TBL_RESERVE_1" FOREIGN KEY (
	BUSNO
)
REFERENCES "TBL_BUS" (
	NO
);

ALTER TABLE "TBL_RESERVE" ADD CONSTRAINT "FK_TBL_TRAIN_TO_TBL_RESERVE_1" FOREIGN KEY (
	TRAINNO
)
REFERENCES "TBL_TRAIN" (
	NO
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_LIKE_1" FOREIGN KEY (
	MEMBERNO
)
REFERENCES "TBL_MEMBER" (
	NO
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_HOTEL_TO_TBL_LIKE_1" FOREIGN KEY (
	HOTELNO
)
REFERENCES "TBL_HOTEL" (
	NO
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_CAMP_TO_TBL_LIKE_1" FOREIGN KEY (
	CAMPNO
)
REFERENCES "TBL_CAMP" (
	NO
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_FESTIVAL_TO_TBL_LIKE_1" FOREIGN KEY (
	FESTIVALNO
)
REFERENCES "TBL_FESTIVAL" (
	NO
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_FOOD_TO_TBL_LIKE_1" FOREIGN KEY (
	FOODNO
)
REFERENCES "TBL_FOOD" (
	NO
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_PARK_TO_TBL_LIKE_1" FOREIGN KEY (
	PARKNO
)
REFERENCES "TBL_PARK" (
	NO
);

ALTER TABLE "TBL_REVIEW" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_REVIEW_1" FOREIGN KEY (
	MEMBERNO
)
REFERENCES "TBL_MEMBER" (
	NO
);

ALTER TABLE "TBL_REVIEW" ADD CONSTRAINT "FK_TBL_HOTEL_TO_TBL_REVIEW_1" FOREIGN KEY (
	HOTELNO
)
REFERENCES "TBL_HOTEL" (
	NO
);

ALTER TABLE "TBL_REVIEW" ADD CONSTRAINT "FK_TBL_CAMP_TO_TBL_REVIEW_1" FOREIGN KEY (
	CAMPNO
)
REFERENCES "TBL_CAMP" (
	NO
);

ALTER TABLE "TBL_REVIEW" ADD CONSTRAINT "FK_TBL_FESTIVAL_TO_TBL_REVIEW_1" FOREIGN KEY (
	FESTIVALNO
)
REFERENCES "TBL_FESTIVAL" (
	NO
);

ALTER TABLE "TBL_REVIEW" ADD CONSTRAINT "FK_TBL_FOOD_TO_TBL_REVIEW_1" FOREIGN KEY (
	FOODNO
)
REFERENCES "TBL_FOOD" (
	NO
);

ALTER TABLE "TBL_REVIEW" ADD CONSTRAINT "FK_TBL_PARK_TO_TBL_REVIEW_1" FOREIGN KEY (
	PARKNO
)
REFERENCES "TBL_PARK" (
	NO
);

ALTER TABLE "TBL_REPLY" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_REPLY_1" FOREIGN KEY (
	MEMBERNO
)
REFERENCES "TBL_MEMBER" (
	NO
);

ALTER TABLE "TBL_REPLY" ADD CONSTRAINT "FK_TBL_PHOTO_TO_TBL_REPLY_1" FOREIGN KEY (
	PHOTONO
)
REFERENCES "TBL_PHOTO" (
	NO
);

ALTER TABLE "TBL_PHOTO" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_PHOTO_1" FOREIGN KEY (
	MEMBERNO
)
REFERENCES "TBL_MEMBER" (
	NO
);

ALTER TABLE "TBL_BOARD" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_BOARD_1" FOREIGN KEY (
	MEMBERNO
)
REFERENCES "TBL_MEMBER" (
    NO
);
